apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bx7n5zicn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bx7n5zicn-python 
  name: bx7n5zicn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bx7n5zicn-python 
